name: Running basic nova tests

on:
  push:
    branches:
      - action_testing

jobs:

  build:

    runs-on: ubuntu-latest
    name: Erlang/OTP 24.1.3

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1.3'
          rebar3-version: '3.17.0'
      - name: Run the Nova installation script
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/novaframework/rebar3_nova/master/install.sh)"
      - name: Create a new nova application
        run: rebar3 new nova my_app
      - name: Compile the app
        run: rebar3 compile
        working-directory: ./my_app
