name: Running basic nova tests

on:
  push:
    branches:
      - acion_testing

jobs:

  build-and-run:

    runs-on: ubuntu-latest
    name: Erlang/OTP 24.1.3

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1.3'
          rebar3-version: '3.17.0'
      - name: Restore dependency/build cache 🗃️
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ hashFiles('**/rebar.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-
            ${{ runner.os }}-mix-
      - name: Run the Nova installation script
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/novaframework/rebar3_nova/master/install.sh)"
      - name: Create a new nova application
        run: rebar3 new nova my_app
      - name: Compile the app
        run: rebar3 release
        working-directory: ./my_app
      - name: Run server and test with curl
        run: |
          ./test daemon &
          sleep 20 &&
          curl http://localhost:8080
        working-directory: ./_build/default/rel/test/bin/
